Bugfix/console log
SpringRoll/Bellhop pull request #55
Opened 2022-02-09 15:56 UTC by khackskjs

to prevent wrong error log with webpack HMR, in my case vue.js web app.
![image](https://user-images.githubusercontent.com/11523968/153238655-47aed8ae-9a23-4f14-af92-022e22d124df.png)

2022-02-11 17:24 UTC, 902seanryan requested changes

2022-02-11 17:24 UTC, 902seanryan commented on src/Bellhop.js
> +          if (data && !data.startsWith('webpack')) {
For now I'm going to request that this additional check be removed. See comment for more info

2022-02-11 17:26 UTC, 902seanryan commented
@khackskjs 
In regards to the `webpack` check. I think that check is just too specific to really require its inclusion. The error is technically correct since we're trying to parse a string rather than stringified JSON. Its just that the message is coming from Webpack not from within the Springroll ecosystem. 
The error itself also shouldn't be halting any execution since its just a `console.error` call. 
If the error message is a bigger problem, feel free to open up an issue and we can have a proper discussion on how best to handle it. 

Thanks again for catching bugs and presenting fixes. Always appreciated!

2022-02-13 12:27 UTC, khackskjs commented
@902seanryan I understand what's your point and I agree that is' too specific case. as you said, it's just log without any collaption. so I suggest simply change log level with warn.
I believe error log is kind of unexpected situation or failed to work in business logic.

2022-02-17 14:47 UTC, deycorinne commented
@902seanryan sounds good to me. let's do it!

2022-02-18 12:25 UTC, khackskjs commented on src/Bellhop.js
> +      this.debug({ isChild: this.isChild, received, message: message });
@902seanryan @deycorinne Please check this line also. 
`false` is suppsed to be removed.
thank you.

2022-02-18 16:05 UTC, 902seanryan approved these changes
@khackskjs Sorry could you point this one to develop as well?

2022-02-18 16:08 UTC, khackskjs commented
Is there anything for me to do to merge blocked PR? 
Reason why I ask you it's my first time to merge blocked PR that I made a PR

2022-03-09 14:41 UTC, merged